// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqiCaUbaVGfXBM22vkoUC9-RzLJaitr1Y',
    appId: '1:113606550175:web:55b36f18ce6a0eb80578aa',
    messagingSenderId: '113606550175',
    projectId: 'i-carros',
    authDomain: 'i-carros.firebaseapp.com',
    storageBucket: 'i-carros.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB7p9z-ekiuqqz8OCghr2WimrZiNYl9yE',
    appId: '1:113606550175:android:e30bb34a8a6d397f0578aa',
    messagingSenderId: '113606550175',
    projectId: 'i-carros',
    storageBucket: 'i-carros.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIiqU3N9JLRdQGsqPC9D8c6GhHIV8bLAs',
    appId: '1:113606550175:ios:1687b5f14f0013810578aa',
    messagingSenderId: '113606550175',
    projectId: 'i-carros',
    storageBucket: 'i-carros.appspot.com',
    iosClientId: '113606550175-sc5k4oo3mv3vo4ki70hrjftifnki67vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.icarros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIiqU3N9JLRdQGsqPC9D8c6GhHIV8bLAs',
    appId: '1:113606550175:ios:1687b5f14f0013810578aa',
    messagingSenderId: '113606550175',
    projectId: 'i-carros',
    storageBucket: 'i-carros.appspot.com',
    iosClientId: '113606550175-sc5k4oo3mv3vo4ki70hrjftifnki67vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.icarros',
  );
}
